language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install flake8
  - pip install pep257
# command to run tests
script:
  - flake8 *.py --max-line-length=120 --ignore=W391,W291
  - pep257 . --ignore=D202
